import { AppointmentPriority, AppointmentStatus, AppointmentType } from "@/src/enum";

export interface PatientRef {
    _id: string;
    fullName: string;
}

export interface ProviderRef {
    _id: string;
    name: string;
}

export interface AppointmentLocation {
    facilityId: string;
    facilityName: string;
    roomNumber: string;
    address: string;
}

export interface AppointmentRequest {
    appointmentNumber: string; // WILL GENERATED BY THE FRONTEND
    patientId: string;  // WILL GET FROM THE GET PROVIDER 
    providerId: string;  // WILL GET FROM THE GET PATIENT
    departmentName: string;
    appointmentDate: string;
    startTime: string;
    endTime: string;
    duration: number;
    timeZone: string;
    type: AppointmentType.CONSULTATION | AppointmentType.EMERGENCY | AppointmentType.FOLLOW_UP | AppointmentType.PROCEDURE;
    priority: AppointmentPriority.HIGH | AppointmentPriority.LOW | AppointmentPriority.MEDIUM | AppointmentPriority.URGENT;
    status: AppointmentStatus.CANCELLED | AppointmentStatus.COMPLETED | AppointmentStatus.NO_SHOW | AppointmentStatus.RESCHEDULED | AppointmentStatus.SCHEDULED;
    location: AppointmentLocation;
    reasonForVisit: string;
    symptoms: string[];
    notes: string;
    createdBy: string;
    updatedBy: string;
}

export interface AppointmentResponse extends AppointmentRequest {
    _id: string;
    patientName: string;
    providerName: string;
    remindersSent: any[];
    createdAt: string; // ISO date string
    updatedAt: string; // ISO date string
    __v: number;
}

export interface AppointmentRequestResponse {
    success: true;
    message: string;
    data: AppointmentResponse;
}

export interface AppointmentRequestErrorResponse {
    success: false;
    message: string;
    data?: string;
}

// Combined response type
export type AppointmentRequestResponseApiResponse = AppointmentRequestResponse | AppointmentRequestErrorResponse;


// Get All Appointments
export interface Appointment {
    _id: string;
    location: AppointmentLocation;
    appointmentNumber: string;
    patientId: PatientRef | null;
    patientName: string;
    providerId: ProviderRef | null;
    providerName: string;
    departmentName: string;
    appointmentDate: string;
    startTime: string;
    endTime: string;
    duration: number;
    timeZone: string;
    type: AppointmentType.CONSULTATION | AppointmentType.EMERGENCY | AppointmentType.FOLLOW_UP | AppointmentType.PROCEDURE;
    priority: AppointmentPriority.HIGH | AppointmentPriority.LOW | AppointmentPriority.MEDIUM | AppointmentPriority.URGENT;
    status: AppointmentStatus.CANCELLED | AppointmentStatus.COMPLETED | AppointmentStatus.NO_SHOW | AppointmentStatus.RESCHEDULED | AppointmentStatus.SCHEDULED;
    reasonForVisit: string;
    symptoms: string[];
    notes: string;
    createdBy: string;
    updatedBy: string;
    remindersSent: any[];
    createdAt: string;
    updatedAt: string;
    __v: number;
}

export interface AppointmentGetAllResponse {
    success: true;
    count: number;
    message?: string;
    data: Appointment[]
}

export interface AppointmentGetErrorResponse {
    success: false;
    message: string;
    data: string;
}

// Combined response type
export type AppointmentGetAllApiResponse = AppointmentGetAllResponse | AppointmentGetErrorResponse;


// Get Appointment by ID
export interface AppointmentGetByIdResponse {
    success: true;
    count: number;
    message?: string;
    data: Appointment
}

// Combined response type
export type AppointmentGetByIdApiResponse = AppointmentGetByIdResponse | AppointmentGetErrorResponse;


// DELETE Appointment
export interface AppointmentDeleteResponse {
    success: boolean;
    message: string;
}

export interface AppointmentDeleteErrorResponse {
    success: false;
    message: string;
    error: any[];
    data?: string;
}

export type AppointmentDeleteApiResponse = AppointmentDeleteResponse | AppointmentDeleteErrorResponse;

// PATCH METHOD CANCEL APPOINTMENT

export interface CancelAppointmentGetResponse {
    success: boolean;
    message: string;
    data: {
        location: AppointmentLocation;
        _id: string;
        appointmentNumber: string;
        patientId: string;
        patientName: string;
        providerId: string;
        providerName: string;
        departmentName: string;
        appointmentDate: string; // ISO string
        startTime: string;
        endTime: string;
        duration: number;
        timeZone: string;
        type: AppointmentType.CONSULTATION | AppointmentType.EMERGENCY | AppointmentType.FOLLOW_UP | AppointmentType.PROCEDURE;
        priority: AppointmentPriority.HIGH | AppointmentPriority.LOW | AppointmentPriority.MEDIUM | AppointmentPriority.URGENT;
        status: AppointmentStatus.CANCELLED | AppointmentStatus.COMPLETED | AppointmentStatus.NO_SHOW | AppointmentStatus.RESCHEDULED | AppointmentStatus.SCHEDULED;
        reasonForVisit: string;
        symptoms: string[];
        notes: string;
        createdBy: string;
        updatedBy: string;
        remindersSent: any[]; // You can type this more strictly if you know the structure
        createdAt: string; // ISO string
        updatedAt: string; // ISO string
        __v: number;
    };
}

export interface CancelAppointmentErrorResponse {
    success: false;
    message: string;
    errors: any[];
}

export type CancelAppointmentApiResponse = CancelAppointmentGetResponse | CancelAppointmentErrorResponse

// PATCH METHOD RESCHEDULE

export interface RescheduleAppointmentRequest {
    newAppointmentDate: string;
    newStartTime: string;
    newEndTime: string;
}

export interface RescheduleAppointmentErrorResponse {
    success: false;
    message: string;
    errors: {
        [field: string]: {
            name: string;
            message: string;
            properties: {
                message: string;
                type: string;
                path: string;
            };
            kind: string;
            path: string;
        };
    };
}

export interface RescheduleAppointmentGetResponse {
    success: boolean;
    message: string;
    data: {
        location: AppointmentLocation;
        _id: string;
        appointmentNumber: string;
        patientId: string;
        patientName: string;
        providerId: string;
        providerName: string;
        departmentName: string;
        appointmentDate: string; // ISO date string
        startTime: string;
        endTime: string;
        duration: number;
        timeZone: string;
        type: string;
        priority: string;
        status: string;
        reasonForVisit: string;
        symptoms: string[];
        notes: string;
        createdBy: string;
        updatedBy: string;
        remindersSent: any[]; // Can be typed strictly if structure is known
        createdAt: string; // ISO date string
        updatedAt: string; // ISO date string
        __v: number;
    };
}

export type RescheduleAppointmentApiResponse = RescheduleAppointmentGetResponse | RescheduleAppointmentErrorResponse

export interface AppointmentFilters {
    patientId?: string;
    providerId?: string;
    status?: Appointment['status'];
    type?: Appointment['type'];
    priority?: Appointment['priority'];
    dateFrom?: string;
    dateTo?: string;
    searchTerm?: string;
}

export interface AppointmentStats {
    total: number;
    scheduled: number;
    confirmed: number;
    cancelled: number;
    completed: number;
    noShow: number;
    rescheduled: number;
}